---
required_debs:
  - python
  - python-django
  - python-lxml
  - python-docutils
  - python-libxml2
  - python-libxslt1
  - python-pypdf
  - python-stdnum
  - default-jre
  - texlive-xetex # contains ucharclasses
  - texlive-latex-extra
  - texlive-latex-recommended
  - texlive-lang-german
  - latexmk
  - ttf-tiresias
  - ttf-mscorefonts-installer # for arial font in large print
  - lmodern
  - xsltproc
  - jing
  - unzip
  - mysql-client
  - python-mysqldb
  - openoffice.org-hyphenation-de # hyphenation patterns
  - python-httplib2 # for talking to alfresco (abacus_import)

apache_debs:
  - apache2
  - libapache2-mod-wsgi

