---
required_debs:
  - python
  - python-django
  - python-lxml
  - python-docutils
  - python-libxml2
  - python-libxslt1
  - python-pypdf
  - python-stdnum
  - default-jre
  - texlive-xetex
  - texlive-latex-extra
  - texlive-latex-recommended
  - texlive-lang-german
  - latexmk
  - ttf-tiresias
  - lmodern
  - xsltproc
  - jing
  - unzip
  - python-cmislib

apache_debs:
  - apache2
  - libapache2-mod-wsgi

