---
- name: download liblouis
  get_url:
    url: "https://github.com/liblouis/liblouis/releases/download/v{{ liblouis_version }}/liblouis-{{ liblouis_version }}.tar.gz"
    dest: "/tmp/liblouis-{{ liblouis_version }}.tar.gz"

- name: Expand liblouis archive
  unarchive:
    src: "/tmp/liblouis-{{ liblouis_version }}.tar.gz"
    dest: /tmp
    creates: "/tmp/liblouis-{{ liblouis_version }}/README"
    copy: no

- name: configure
  command: ./configure --enable-ucs4
  args:
    chdir: "/tmp/liblouis-{{ liblouis_version }}"
    creates: "/tmp/liblouis-{{ liblouis_version }}/liblouis/config.h"
  register: configure_liblouis

- name: build and install liblouis
  command: make {{ item }}
  args:
    chdir: "/tmp/liblouis-{{ liblouis_version }}"
  with_items:
    - all
    - install
  when: configure_liblouis.changed

- name: run ldconfig
  command: ldconfig
  when: configure_liblouis.changed

- name: install Python bindings
  command: python setup.py install
  args:
    chdir: "/tmp/liblouis-{{ liblouis_version }}/python"
    creates: "/usr/local/lib/python2.7/dist-packages/louis-{{ liblouis_version }}.egg-info"

- name: install Python3 bindings
  command: python3 setup.py install
  args:
    chdir: "/tmp/liblouis-{{ liblouis_version }}/python"
    creates: "/usr/local/lib/python3.8/dist-packages/louis-{{ liblouis_version }}.egg-info"

- name: install sbs tables
  apt:
    deb: https://github.com/sbsdev/sbs-braille-tables/releases/download/v{{ sbs_braille_tables_version }}/sbs-braille-tables_{{ sbs_braille_tables_version }}_all.deb
  notify:
    - restart apache
