---
- hosts: repo
  sudo: yes

  tasks:
    - name: copy staging debs
      copy: src=files/{{ item }} dest=/tmp/debs/
      with_items: staging_debs
      notify:
        - re-index staging repo

    - name: copy production debs
      copy: src=files/{{ item }} dest=/tmp/debs/
      with_items: production_debs
      notify:
        - re-index production repo

  handlers:
    - name: re-index staging repo
      shell: "reprepro -b /var/www/apt -S contrib -P optional includedeb testing /tmp/debs/*"

    - name: re-index production repo
      shell: "reprepro -b /var/www/apt -S contrib -P optional includedeb production /tmp/debs/*"

