---
- hosts: daisyproducer
  become: true
  vars_files:
    - "vars/passwords.yml"
  
  roles:
    - pipeline1

  tasks:
    
    - name: copy debs
      copy: src="files/{{ item }}" dest=/tmp
      with_items: debs

    - name: make sure we have default-jdk
      apt: name=default-jdk

    # most dependencies are packaged as debs
    - name: install debs
      # this should really work with the apt module but alas it doesn't
      # apt: deb="/tmp/{{ item }}" 
      command: dpkg --skip-same-version -i "/tmp/{{ item }}"
      with_items: debs
      notify:
        - restart apache

    - name: deploy dtbook hyphenator
      unarchive: src=files/dtbook_hyphenator.zip dest=/opt
      notify:
        - restart apache

    # install the daisyproducer web app
    - name: pull daisyproducer from git
      git: repo=https://github.com/sbsdev/daisyproducer.git 
           dest={{ daisyproducer_app_path }}
           force=yes
      register: install_daisyproducer
      notify:
        - restart apache

    - name: adapt local settings for daisyproducer
      template: src=templates/settings_local.j2 
                dest={{ daisyproducer_app_path }}/daisyproducer/settings_local.py
                backup=yes
                mode=644
      when: install_daisyproducer.changed

    - name: build localized daisyproducer messages
      command: django-admin compilemessages chdir={{ daisyproducer_app_path }}/daisyproducer
      when: install_daisyproducer.changed

    - name: migrate daisyproducer db
      django_manage: command=migrate app_path={{ daisyproducer_app_path }}
      when: install_daisyproducer.changed

    - name: fix daisyproducer app path in abacus_import cron job
      lineinfile: dest={{ daisyproducer_app_path }}/daisyproducer/abacus_import/misc/cron.d/daisyproducerImportABACUSProductData
                  regexp='^INSTALLDIR=/path/to/daisyproducer$' 
                  line='INSTALLDIR={{ daisyproducer_app_path }}'
      when: install_daisyproducer.changed

    - name: add a cron job to run the daisyproducer ABACUS import
      cron: name="run the daisyproducer ABACUS import every 10 minutes on weekdays" 
            minute="*/10" hour="6-20" weekday="1-5"
            cron_file="daisyproducerImportABACUSProductData"
            user="www-data"
            job="{{ daisyproducer_app_path }}/daisyproducer/abacus_import/misc/cron.d/daisyproducerImportABACUSProductData > /dev/null 2>&1"

    - name: fix daisyproducer app path in clean_excess_document_versions cron job
      lineinfile: dest={{ daisyproducer_app_path }}/daisyproducer/documents/misc/cron.d/daisyproducer_clean_excess_document_versions
                  regexp='^INSTALLDIR=/path/to/daisyproducer$' 
                  line='INSTALLDIR={{ daisyproducer_app_path }}'
      when: install_daisyproducer.changed

    - name: add a cron job to clean out excess old versions
      cron: name="Clean out old versions from the database and the file system" 
            special_time=weekly
            cron_file="daisyproducerCleanOldVersions"
            user="www-data"
            job="{{ daisyproducer_app_path }}/daisyproducer/documents/misc/cron.d/daisyproducer_clean_excess_document_versions > /dev/null 2>&1"

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
