---
- hosts: kati
  become: true
  vars_files:
    - "vars/passwords.yml"
  roles:
    - kati

  tasks:
    - name: copy stone font debian package
      copy: src=ttf-stonesans_0.1-2_all.deb dest=/tmp

    - name: install stone font debian package
      apt: deb=/tmp/ttf-stonesans_0.1-2_all.deb

    - name: install other fonts
      apt:
        name:
          - ttf-mscorefonts-installer
          - ttf-tiresias
