---
- hosts: pipeline
  become: true
  roles:
    - java8

  tasks:
    - name: install lame
      apt: name=lame

    # in some cases it is beneficial to remove the pipeline database
    # (to get rid of old jobs, etc). But this causes problems when the
    # deb isn't actually reinstalled and we restart the service.
    # - name: remove database
    #   file: path=/var/opt/daisy-pipeline2 state=absent

    - name: copy deb
      copy: src="{{ pipeline2_deb }}" dest=/tmp

    - name: install pipeline2
      apt: deb="/tmp/{{ pipeline2_deb }}"
      notify:
        - restart pipeline2

    - name: set REMOTE=false for pipeline2
      lineinfile: dest=/etc/default/pipeline2d
                  line='REMOTE=false'
      notify:
        - restart pipeline2

    - name: set memory for pipeline2
      lineinfile: dest=/etc/default/pipeline2d
                  line='export JAVA_MAX_MEM=2G'
      notify:
        - restart pipeline2

    # - name: set liblouis.external to true
    #   # not sure if this is really needed. AFAIK liblouis comes with the
    #   # braille modules. See
    #   # https://github.com/sbsdev/deployment/blob/master/src/plans/pipeline2.clj#L31
    #   lineinfile: dest="{{ daisy_pipeline2_path }}/pipeline.properties"
    #               line='org.daisy.pipeline.liblouis.external=true'

    - name: copy webui deb
      copy: src="{{ pipeline2_webui_deb }}" dest=/tmp

    - name: install webui
      apt: deb="/tmp/{{ pipeline2_webui_deb }}"
      notify:
        - restart pipeline2_webui

  handlers:
    - name: restart pipeline2
      service: name=daisy-pipeline2 state=restarted

    - name: restart pipeline2_webui
      service: name=daisy-pipeline2-webui state=restarted
