---

- name: enable jessie backports
  apt_repository: repo='deb http://ftp.debian.org/debian jessie-backports main'
  when: ansible_lsb.major_release|int >= 8

- name: install Java8
  apt: name=openjdk-8-jre
  when: ansible_lsb.major_release|int >= 8

- name: set java to the right version
  alternatives: name=java path=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  when: ansible_lsb.major_release|int >= 8

# on Debian Wheezy just install Java 7 and hope the requested Wildfly
# version works with it

- name: install Java7
  apt: name=openjdk-7-jre
  when: ansible_lsb.major_release|int < 8

- name: set java to the right version
  alternatives: name=java path=/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
  when: ansible_lsb.major_release|int < 8

- name: download wildfly
  get_url: url={{ wildfly_url }}
           dest=/tmp/wildfly-{{ wildfly_version }}.tar.gz

- name: create a wildfly group
  group: name=wildfly system=yes gid=35

- name: create a wildfly user
  user: name=wildfly system=yes uid=35 group=wildfly home=/opt/wildfly createhome=no

- name: install wildfly
  unarchive: src=/tmp/wildfly-{{ wildfly_version }}.tar.gz
             copy=no
             dest={{ wildfly_prefix }}
             owner={{ wildfly_user }} group={{ wildfly_group }}
             creates={{ wildfly_prefix }}/wildfly-{{ wildfly_version }}/standalone/configuration/standalone-full.xml
  register: install_wildfly

- name: create a symlink
  file: path={{ wildfly_prefix }}/wildfly
        src={{ wildfly_prefix }}/wildfly-{{ wildfly_version }}
        owner={{ wildfly_user }} group={{ wildfly_group }}
        state=link

- name: make sure wildfly gets enough memory
  template: src=standalone.conf.j2
            dest={{ wildfly_prefix }}/wildfly/bin/standalone.conf

- name: create wildfly defaults file
  template: src=wildfly.conf.j2
            dest=/etc/default/wildfly

- name: create startup script
  template: src=wildfly-init-debian.sh.j2
            dest=/etc/init.d/wildfly
            mode=0755

- name: enable the wildfly service
  service: name=wildfly enabled=yes

- name: add an admin user to be able to access the wildfly admin console
  shell: "{{ wildfly_prefix }}/wildfly/bin/add-user.sh --silent -u {{ wildfly_admin_user }} -p {{ wildfly_admin_password }}"

- name: start the wildfly service
  service: name=wildfly state=started

- name: download database driver
  get_url: url=http://search.maven.org/remotecontent?filepath=mysql/mysql-connector-java/{{ mysql_connector_version }}/mysql-connector-java-{{ mysql_connector_version }}.jar
           dest=/tmp/mysql-connector-java-{{ mysql_connector_version }}.jar

- name: create config file for wildfly cli
  template: src=configure_wildfly_standalone.cli.j2
            dest=/tmp/configure_wildfly_standalone.cli

- name: configure system properties and datasources
  command: "{{ wildfly_prefix }}/wildfly/bin/jboss-cli.sh --file=/tmp/configure_wildfly_standalone.cli"
  when: install_wildfly.changed
