groups:
  - name: main
    rules:
      - alert: FailingFunctions
        expr: fn_runs_total{result!="success"}
        labels:
          severity: warning
        annotations:
          summary: Functions are failing
          description: "Functions are failing\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: JvmMemoryFillingUp
        expr: (sum by (instance)(jvm_memory_used_bytes{area="heap"}) / sum by (instance)(jvm_memory_max_bytes{area="heap"})) * 100 > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: JVM memory filling up (instance {{ $labels.instance }})
          description: "JVM memory is filling up (> 80%)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      # see https://awesome-prometheus-alerts.grep.to/rules.html#host-and-hardware
      # Same rule using "node_filesystem_avail" will fire when disk fills for root users.
      - alert: HostOutOfDiskSpace
        expr: (node_filesystem_free * 100) / node_filesystem_size < 10 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host out of disk space (instance {{ $labels.instance }})
          description: "Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: HostHighCpuLoad
        expr: 100 - (avg by(instance) (rate(node_cpu{mode="idle"}[2m])) * 100) > 80
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Host high CPU load (instance {{ $labels.instance }})
          description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

