---
- name: restart daisyproducer2
  service:
    daemon_reload: yes
    name: daisyproducer2
    state: restarted

- name: restart nginx
  service:
    daemon_reload: yes
    name: nginx
    state: restarted
