---

- name: Create the install directory
  file:
    path: "{{ hyphenator_install_dir }}"
    state: directory
  notify:
    - restart apache

- name: Download the jar file
  get_url:
    url: https://github.com/sbsdev/dtbook_hyphenator/releases/download/{{ hyphenator_version }}/dtbook-hyphenator-{{ hyphenator_version }}-shaded.jar
    dest: "{{ hyphenator_install_dir }}/dtbook-hyphenator.jar"

- name: copy deb for spelling
  copy: src="{{ item }}" dest=/tmp
  with_items: "{{ hyphenator_debs }}"
  register: copy_deb

- name: install spelling hyphenation tables
  apt: deb="/tmp/{{ item }}"
  with_items: "{{ hyphenator_debs }}"
  when: copy_deb.changed

- name: make sure we have /usr/share/libhyphen/substrings.pl
  apt: name=libhyphen-dev

- name: create a directory for the generated hyphenation tables
  file:
    path: /usr/share/hyphen/generated
    state: directory
    mode: 0755

- name: Move the existing hyphen dicts to the generated directory
  copy:
    src: '/usr/share/hyphen/{{ item }}'
    dest: '/usr/share/hyphen/generated/{{ item }}'
    remote_src: True
  with_items:
    - "hyph_de_DE.dic"
    - "hyph_de_DE_OLDSPELL.dic"

- name: replace old hyphen dicts with links to the generated ones
  file:
    path: '/usr/share/hyphen/{{ item }}'
    src: '/usr/share/hyphen/generated/{{ item }}'
    state: link
    force: yes
  with_items:
    - "hyph_de_DE.dic"
    - "hyph_de_DE_OLDSPELL.dic"

