---
daisyproducer2_version: 0.9.4
daisyproducer2_install_dir: /usr/local/share/java
hyphen_deb_version: 1.1-2
online_player_spool_dir: /var/spool/ebooks/
generated_resources_spool_dir: /var/tmp/daisyproducer2

