---

- name: install prometheus server
  apt:
    pkg:
      - prometheus
      - prometheus-alertmanager

- name: create alerting rules
  copy:
    src: alert.rules.yml
    dest: /etc/prometheus/alert.rules.yml
  notify:
    - restart prometheus

- name: create config file for prometheus
  template: src=prometheus.yml.j2
            dest=/etc/prometheus/prometheus.yml
  notify:
    - restart prometheus

- name: create config file for prometheus alertmanager
  template: src=alertmanager.yml.j2
            dest=/etc/prometheus/alertmanager.yml
  notify:
    - restart alertingmanager

