---

- name: install dependencies
  apt: name="{{ pipeline1_required_debs }}"

- name: copy pipeline1 deb
  copy:
    src: files/{{ pipeline1_deb }}
    dest: /tmp
  register: copy_deb

- name: install pipeline1 deb
  apt: deb="/tmp/{{ pipeline1_deb }}"
  when: copy_deb.changed

- name: adapt the settings
  template:
    src: pipeline.user.properties.j2
    dest: /usr/lib/daisy-pipeline/pipeline.user.properties
    mode: 0644

# copy the sbs specific dtbook2latex so that it is picked up by the transformer
- name: copy dtbook2latex_sbs.xsl
  command: cp dtbook2latex_sbs.xsl dtbook2latex.xsl
           chdir=/usr/lib/daisy-pipeline/transformers/se_tpb_dtbook2latex
  when: copy_deb.changed

