---

- name: make sure we have default-jdk
  apt: name=default-jdk

- name: pipeline2 needs a ruby interpreter
  apt: name=ruby1.9.1

- name: copy deb
  copy: src="{{ pipeline1_deb }}" dest=/tmp
  register: copy_deb

- name: install pipeline1
  command: dpkg -i "/tmp/{{ pipeline1_deb }}"
  when: copy_deb.changed

# copy the sbs specific dtbook2latex so that it is picked up by the transformer
- name: copy dtbook2latex_sbs.xsl
  command: cp dtbook2latex_sbs.xsl dtbook2latex.xsl
           chdir=/usr/lib/daisy-pipeline/transformers/se_tpb_dtbook2latex
  when: copy_deb.changed

