---

- name: install dependencies
  apt: name="{{ pipeline1_required_debs }}"

- name: install Pipeline1
  apt:
    deb: https://github.com/sbsdev/pipeline1/releases/download/{{ pipeline1_version }}/daisy-pipeline_{{ pipeline1_version }}-2_all.deb
  register: install_deb

- name: adapt the settings
  template:
    src: pipeline.user.properties.j2
    dest: /usr/lib/daisy-pipeline/pipeline.user.properties
    mode: 0644

# copy the sbs specific dtbook2latex so that it is picked up by the transformer
- name: copy dtbook2latex_sbs.xsl
  command: cp dtbook2latex_sbs.xsl dtbook2latex.xsl
           chdir=/usr/lib/daisy-pipeline/transformers/se_tpb_dtbook2latex
  when: install_deb.changed

