---

- name: install dependencies
  apt: name="{{ pipeline1_required_debs }}"

- name: copy local debs
  copy: src="{{ item }}" dest=/tmp
  register: copy_deb
  with_items: "{{ pipeline1_local_debs }}"

- name: install local debs
  apt: deb="/tmp/{{ item }}"
  when: copy_deb.changed
  with_items: "{{ pipeline1_local_debs }}"

- name: adapt the settings
  template:
    src: pipeline.user.properties.j2
    dest: /usr/lib/daisy-pipeline/pipeline.user.properties
    mode: 0644

# copy the sbs specific dtbook2latex so that it is picked up by the transformer
- name: copy dtbook2latex_sbs.xsl
  command: cp dtbook2latex_sbs.xsl dtbook2latex.xsl
           chdir=/usr/lib/daisy-pipeline/transformers/se_tpb_dtbook2latex
  when: copy_deb.changed

