---
- name: install Pipeline2
  apt:
    deb: https://github.com/daisy/pipeline-assembly/releases/download/v{{ pipeline2_version }}/pipeline2-{{ pipeline2_version }}_debian.deb
  when: pipeline2_deb is undefined

- name: install old version Pipeline2
  apt:
    deb: "{{ pipeline2_deb }}"
  when: pipeline2_deb is defined

# in some cases it is beneficial to remove the pipeline database
# (to get rid of old jobs, etc). But this causes problems when the
# deb isn't actually reinstalled and we restart the service.
# - name: remove database
#   file: path="{{ daisy_pipeline2_path }}"
#         state=absent

- name: set REMOTE=true for pipeline2
  lineinfile:
    path: /etc/default/daisy-pipeline2
    regexp: "^#?REMOTE=(true|false)$"
    line: 'REMOTE=true'
  notify:
    - restart pipeline2

- name: set memory for pipeline2
  lineinfile:
    path: /etc/default/daisy-pipeline2
    line: 'export JAVA_MAX_MEM=2G'
  notify:
    - restart pipeline2

# the location of the properties file has changed in version 1.14.1
- name: set config file to pipeline.properties
  set_fact:
    pipeline_config_file: "{{ daisy_pipeline2_path }}/pipeline.properties"
  when: "pipeline2_version is version('1.14.1', '>=')"

- name: set config file to system.properties
  set_fact:
    pipeline_config_file: "{{ daisy_pipeline2_path }}/system.properties"
  when: "pipeline2_version is version('1.14.1', '<')"

- name: disallow local filesystem interactions
  lineinfile: dest="{{ pipeline_config_file }}"
              regexp='^#?org.daisy.pipeline.ws.localfs='
              line='org.daisy.pipeline.ws.localfs=false'
  notify:
    - restart pipeline2

- name: set authentication to false
  lineinfile: dest="{{ pipeline_config_file }}"
              regexp='^#?org.daisy.pipeline.ws.authentication='
              line='org.daisy.pipeline.ws.authentication=false'
  notify:
    - restart pipeline2

- name: set client secret in server
  lineinfile: dest="{{ pipeline_config_file }}"
              regexp='^org.daisy.pipeline.ws.authentication.secret='
              line='org.daisy.pipeline.ws.authentication.secret={{ pipeline2_client_secret }}'
  notify:
    - restart pipeline2

- name: set liblouis.external to true
  # not sure if this is really needed. AFAIK liblouis comes with the
  # braille modules. See
  # https://github.com/sbsdev/deployment/blob/master/src/plans/pipeline2.clj#L31
  lineinfile: dest="{{ pipeline_config_file }}"
              line='org.daisy.pipeline.liblouis.external=true'

# install sbs specific pipeline modules
- name: install sbs pipeline module debs
  apt:
    deb: "{{ item }}"
  with_items:
    - "{{ sbs_module_debs }}"

- name: create the runit startup scripts
  include_tasks: runit.yml
  when: host_has_runit
