---
- name: install Pipeline2
  apt:
    deb: https://github.com/daisy/pipeline-assembly/releases/download/v{{ pipeline2_version }}/pipeline2-{{ pipeline2_version }}_debian.deb
  when: pipeline2_deb is undefined

- name: install old version Pipeline2
  apt:
    deb: "{{ pipeline2_deb }}"
  when: pipeline2_deb is defined

- name: set defauls file for Pipeline2
  template:
    src: daisy-pipeline2.default.j2
    dest: /etc/default/daisy-pipeline2
    mode: '0644'

# the location of the properties file has changed in version 1.14.1
- name: set config file to pipeline.properties
  set_fact:
    pipeline_config_file: "{{ daisy_pipeline2_path }}/pipeline.properties"
  when: "pipeline2_version is version('1.14.1', '>=')"

- name: set config file to system.properties
  set_fact:
    pipeline_config_file: "{{ daisy_pipeline2_path }}/system.properties"
  when: "pipeline2_version is version('1.14.1', '<')"

- name: disallow local filesystem interactions
  lineinfile: dest="{{ pipeline_config_file }}"
              regexp='^#?org.daisy.pipeline.ws.localfs='
              line='org.daisy.pipeline.ws.localfs=false'
  notify:
    - restart pipeline2

- name: set authentication to false
  lineinfile: dest="{{ pipeline_config_file }}"
              regexp='^#?org.daisy.pipeline.ws.authentication='
              line='org.daisy.pipeline.ws.authentication=false'
  notify:
    - restart pipeline2

- name: set client secret in server
  lineinfile: dest="{{ pipeline_config_file }}"
              regexp='^org.daisy.pipeline.ws.authentication.secret='
              line='org.daisy.pipeline.ws.authentication.secret={{ pipeline2_client_secret }}'
  notify:
    - restart pipeline2

- name: set liblouis.external to true
  # not sure if this is really needed. AFAIK liblouis comes with the
  # braille modules. See
  # https://github.com/sbsdev/deployment/blob/master/src/plans/pipeline2.clj#L31
  lineinfile: dest="{{ pipeline_config_file }}"
              line='org.daisy.pipeline.liblouis.external=true'

# install sbs specific pipeline modules
- name: install sbs pipeline module debs
  apt:
    deb: "{{ item }}"
  with_items:
    - "{{ sbs_module_debs }}"

# - name: Stop the system V service
#   sysvinit:
#     name: daisy-pipeline2
#     state: stopped
#     enabled: no
#   when: install_deb.changed

# FIXME: Do not remove the system V init file for now as the pipeline2
# systemd service just adds a layer on top of it (at least for now)
# - name: Remove the system V init file
#   file:
#     path: /etc/init.d/daisy-pipeline2
#     state: absent

# Install the pipeline2 systemd service
- name: Install the Pipeline2 systemd service
  template:
    src: daisy-pipeline2.service.j2
    dest: /etc/systemd/system/daisy-pipeline2.service
    mode: '0644'
  notify:
    - restart pipeline2

- name: Enable and start the service
  systemd:
    name: daisy-pipeline2
    enabled: yes
    state: started

# Make Pipeline2 logs available under /var/log even on a system with systemd
- name: install rsyslog
  apt:
    name: rsyslog

