---
- name: copy deb
  copy: src="{{ pipeline2_deb }}" dest=/tmp

- name: install pipeline2
  apt: deb="/tmp/{{ pipeline2_deb }}"

# in some cases it is beneficial to remove the pipeline database
# (to get rid of old jobs, etc). But this causes problems when the
# deb isn't actually reinstalled and we restart the service.
# - name: remove database
#   file: path="{{ daisy_pipeline2_path }}"
#         state=absent

- name: set REMOTE=false for pipeline2
  lineinfile:
    path: /etc/default/daisy-pipeline2
    regexp: "^#?REMOTE=(true|false)$"
    line: 'REMOTE=false'
  notify:
    - restart pipeline2

- name: set memory for pipeline2
  lineinfile:
    path: /etc/default/daisy-pipeline2
    line: 'export JAVA_MAX_MEM=2G'
  notify:
    - restart pipeline2

# FIXME: is this still needed? Why do we need to set the client_secret
# if we do not even install the cli client?
- name: set client secret in server
  lineinfile: dest="{{ daisy_pipeline2_path }}/system.properties"
              regexp='^org.daisy.pipeline.ws.authentication.secret='
              line='org.daisy.pipeline.ws.authentication.secret={{ pipeline2_client_secret }}'
  notify:
    - restart pipeline2

- name: set liblouis.external to true
  # not sure if this is really needed. AFAIK liblouis comes with the
  # braille modules. See
  # https://github.com/sbsdev/deployment/blob/master/src/plans/pipeline2.clj#L31
  lineinfile: dest="{{ daisy_pipeline2_path }}/system.properties"
              line='org.daisy.pipeline.liblouis.external=true'

- name: create the runit startup scripts
  template:
    src: runit-run.j2
    dest: /etc/sv/daisy-pipeline2/run
    mode: 0755

- name: enable the daisy-pipeline2 service
  runit:
    name: "daisy-pipeline2"
    enabled: "yes"

# install odt pipeline module
- name: copy odt pipeline module deb
  copy: src="{{ odt_module_deb }}" dest=/tmp

- name: install odt pipeline module
  apt: deb="/tmp/{{ odt_module_deb }}"
