---

- name: create an install directory
  file:
    path: "{{ kati_install_dir }}"
    state: directory

- name: Download the jar file
  get_url:
    url: https://github.com/sbsdev/catalog/releases/download/{{ kati_version }}/catalog.jar
    dest: "{{ kati_install_dir }}/kati-{{ kati_version }}.jar"
  notify:
    - restart kati

- name: create a version independent link to the jar file
  file:
    src: "kati-{{ kati_version }}.jar"
    dest: "{{ kati_install_dir }}/kati.jar"
    state: link

- name: create a config directory
  file:
    path: /etc/kati
    state: directory

- name: create a config file
  template:
    src: config.edn.j2
    dest: /etc/kati/config.edn
    mode: '0600'
  notify:
    - restart kati

- name: Install kati systemd service
  template:
    src: kati.service.j2
    dest: /etc/systemd/system/kati.service
    mode: '0644'
  notify:
    - restart kati

- name: Enable and start the service
  systemd:
    name: kati
    enabled: yes
    state: started

- name: create an sites available file for nginx
  template:
    src: sites-available.j2
    dest: /etc/nginx/sites-available/kati
    mode: '0644'
  notify:
    - restart nginx

- name: create a link in sites enabled for nginx
  file:
    src: /etc/nginx/sites-available/kati
    dest: /etc/nginx/sites-enabled/kati
    owner: root
    group: root
    state: link
  notify:
    - restart nginx

